config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  root 'posts#index'
  resources :posts, only: %i[new create index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts

  validates :username, :name, presence: true
  validates :username, length: { maximum: 30 }
  validates :username, uniqueness: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :member

  def preview
    if body.length > 200
      body[0..200] + '...'
    else
      body
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_params, if: :devise_controller?

  protected

  def configure_permitted_params
    added_params = %i[name username]
    devise_parameter_sanitizer.permit(:sign_up, keys: added_params)
    devise_parameter_sanitizer.permit(:account_update, keys: added_params)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_member!, except: [:index]

  include PostsHelper

  def index
    @posts = Post.all
  end

  def show; end

  def new
    @post = Post.new
  end

  def create
    @post = current_member.posts.build(post_params)

    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_params
    params.require(:post).permit(:body)
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm bg-info">
  <div class="navbar-nav">
    <%= link_to root_path, class: 'navbar-link' do %>
      <h1 class="title">Members Only</h1>
    <% end %>
  </div>

  <div class="navbar-nav">
    <div class="navbar-item">
      <div class="navbar-link p-3">
        <div class="field d-flex flex-row">
          <p class="control">
            <%= link_to "New Post", new_post_path, class: "button text-white p-2" %>
          </p>
          <% if member_signed_in? %>
            <p class="control">
              <%= link_to current_member.username, edit_member_registration_path, class: 'button text-white' %>
            </p>
            <p class="control">
              <%= link_to "Sign Out", destroy_member_session_path, method: :delete, class: 'button text-white' %>
            </p>
          <% else %>
            <p class="control">
              <%= link_to 'Sign In', new_member_session_path, class: 'button text-white p-2' %> 
            </p>
            <p class="control">
              <%= link_to 'Sign Up', new_member_registration_path, class: 'button text-white p-2' %> 
            </p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag  href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" %> 
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="mb-0 bg-primary">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="mb-0 bg-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <%= render 'layouts/navbar' %>

    <%= yield %>
  </body>

</html>

app/views/posts/_form.html.erb
<%= form_with model: @post do |f| %> 
  <%= f.label :body, "Mean Article goes here:" %><br>
  <%= f.text_area :body, placeholder: 'I think Charles is...', size: '70x20' %><br>
  <hr>

  <%= f.submit 'Send' %>

<% end %>

app/views/posts/_post.html.erb
<div class="block">
  <%= link_to posts_path(post) do %>
    <div class="box">
      <article class="media">
        <div class="media-content">
          <div class="content">
            <div class="body">
              <%= post.preview %>
            </div>
            <hr>
            <div class="member">
              <p class="content is-small">
                Posted by:
                <% if member_signed_in? %>
                  <%= post.member.name %>
                <% else %>
                  Anonymous
                <% end %></p> 
            </div>
          </div>
        </div>
      </article>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class="section">
  <div class="container is-centered">
    <h1 class="title is-1">Edit your Post</h1>

    <%= render 'form' %>

  </div>
</div>

app/views/posts/index.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-half">
        <h1 class="title is-2">Posts</h1>
        <%= render @posts %>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="section">
  <div class="container is-centered">
    <h1 class="title is-1">Create A New Post</h1>

    <%= render 'form' %>

  </div>
</div>

app/views/posts/show.html.erb
<div class="section">
  <div class="container is-centered">
    <div class="card">
      <div class="card-content">
        <div class="content is-medium">
          <div class="body">
            <%= simple_format @post.body %>
          </div>
        </div>
        <hr>
        <div class="member">
          Posted by:
          <% if member_signed_in? %>
            <%= @post.member.name %>
          <% else %>
            Anonymous
          <% end %>
        </div>
      </div>
      <footer class="card-footer">
        <p class="card-footer-item">
          <%= link_to posts_path do %>
            <button class="button is-primary is-outlined">
              All Posts
            </button>
          <% end %>
        </p>
        <% if current_member == @post.member %>
          <p class="card-footer-item">
            <%= link_to edit_post_path(@post), class: "level-item" do %>
              <span class="icon">
                <i class="fa fa-pencil" area-hidden="true"></i>
              </span>
              <% end %>
              </p>

              <p class="card-footer-item">
            <%= link_to post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class: "level-item" do %>
              <span class="icon">
                <i class="fa fa-trash"></i>
              </span>
            <% end %>
          </p>
        <% end %>
      </footer>
    </div>
  </div>
</div>